import type { QueryInterface } from 'sequelize'

export async function up(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.bulkInsert('menus', [
    {
      parentId: 0,
      name: '系统管理',
      path: '/system',
      icon: 'Setting',
      type: 'C',
      sort: 1,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 0,
      name: '仪表盘',
      path: '/dashboard',
      component: 'views/Dashboard.vue',
      icon: 'Odometer',
      type: 'M',
      sort: 0,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '基础设置',
      path: '/settings',
      component: 'views/Settings.vue',
      icon: 'Setting',
      type: 'M',
      sort: 0,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '用户管理',
      path: '/users',
      component: 'views/UserList.vue',
      icon: 'User',
      type: 'M',
      sort: 1,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '部门管理',
      path: '/depts',
      component: 'views/DeptManager.vue',
      icon: 'Share',
      type: 'M',
      sort: 2,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '角色管理',
      path: '/roles',
      component: 'views/RoleManager.vue',
      icon: 'Avatar',
      type: 'M',
      sort: 3,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '菜单管理',
      path: '/menus',
      component: 'views/MenuList.vue',
      icon: 'Grid',
      type: 'M',
      sort: 4,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '字典管理',
      path: '/dict',
      component: 'views/DictManager.vue',
      icon: 'Collection',
      type: 'M',
      sort: 5,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '文件管理',
      path: '/files',
      component: 'views/FileManager.vue',
      icon: 'FolderOpened',
      type: 'M',
      sort: 6,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '通知管理',
      path: '/notices',
      component: 'views/NoticeManager.vue',
      icon: 'Bell',
      type: 'M',
      sort: 7,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '系统日志',
      path: '/logs',
      component: 'views/SystemLog.vue',
      icon: 'Document',
      type: 'M',
      sort: 10,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '消息通知',
      path: '/messages',
      component: 'views/MessageList.vue',
      icon: 'ChatLineSquare',
      type: 'M',
      sort: 11,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 1,
      name: '定时任务',
      path: '/tasks',
      component: 'views/TaskManager.vue',
      icon: 'Clock',
      type: 'M',
      sort: 12,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 0,
      name: '系统监控',
      path: '/monitor',
      icon: 'Monitor',
      type: 'C',
      sort: 2,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 14,
      name: '在线用户',
      path: '/online-users',
      component: 'views/OnlineUsers.vue',
      icon: 'Connection',
      type: 'M',
      sort: 0,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
    {
      parentId: 14,
      name: '服务监控',
      path: '/server-monitor',
      component: 'views/ServerMonitor.vue',
      icon: 'DataBoard',
      type: 'M',
      sort: 1,
      status: 1,
      hidden: 0,
      createdAt: new Date(),
      updatedAt: new Date(),
    },
  ])
}

export async function down(queryInterface: QueryInterface): Promise<void> {
  await queryInterface.sequelize.query('DELETE FROM menus WHERE id <= ?', {
    replacements: [16],
  })
}