export * from '../shared/schemas/common.js'
export * from '../shared/schemas/auth.js'
export * from '../shared/schemas/dept.js'
export * from '../shared/schemas/user.js'
export * from '../shared/schemas/role.js'
export * from '../shared/schemas/menu.js'
export * from '../shared/schemas/notice.js'
export * from '../shared/schemas/dict.js'